In [27]:
import pandas as pd

In [28]:
dataset=pd.read_csv("kidney_disease.csv")

In [29]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
id                400 non-null int64
age               391 non-null float64
bp                388 non-null float64
sg                353 non-null float64
al                354 non-null float64
su                351 non-null float64
rbc               248 non-null object
pc                335 non-null object
pcc               396 non-null object
ba                396 non-null object
bgr               356 non-null float64
bu                381 non-null float64
sc                383 non-null float64
sod               313 non-null float64
pot               312 non-null float64
hemo              348 non-null float64
pcv               330 non-null object
wc                295 non-null object
rc                270 non-null object
htn               398 non-null object
dm                398 non-null object
cad               398 non-null object
appet             399 non-null object
pe                399 non-null object
ane               399 non-null object
classification    400 non-null object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [5]:
dataset.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [6]:
dataset.dtypes

id                  int64
age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                object
pc                 object
pcc                object
ba                 object
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv                object
wc                 object
rc                 object
htn                object
dm                 object
cad                object
appet              object
pe                 object
ane                object
classification     object
dtype: object

In [7]:
for columnName in dataset.columns:
     print(columnName)

id
age
bp
sg
al
su
rbc
pc
pcc
ba
bgr
bu
sc
sod
pot
hemo
pcv
wc
rc
htn
dm
cad
appet
pe
ane
classification

In [8]:

if(dataset["age"].dtypes=='O'):
    print("Qual")
else:
    print("Quan")

Quan

In [9]:
Quan=[]
Qual=[]
for columnName in dataset.columns:
    #print(columnName)

    if(dataset[columnName].dtypes=='O'):
        #print("Qual")
        Qual.append(columnName)
    else:
        #print("Quan")
        Quan.append(columnName)

In [10]:
Quan

['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']

In [11]:
Qual

['rbc',
 'pc',
 'pcc',
 'ba',
 'pcv',
 'wc',
 'rc',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

In [12]:
def QuanQual(dataset):
    Quan=[]
    Qual=[]
    for columnName in dataset.columns:
        #print(columnName)

        if(dataset[columnName].dtypes=='O'):
            #print("Qual")
            Qual.append(columnName)
        else:
            #print("Quan")
            Quan.append(columnName)
    return Quan,Qual

In [13]:
QuanQual(dataset)

(['id',
  'age',
  'bp',
  'sg',
  'al',
  'su',
  'bgr',
  'bu',
  'sc',
  'sod',
  'pot',
  'hemo'],
 ['rbc',
  'pc',
  'pcc',
  'ba',
  'pcv',
  'wc',
  'rc',
  'htn',
  'dm',
  'cad',
  'appet',
  'pe',
  'ane',
  'classification'])

In [14]:
QuanQual=QuanQual(dataset)

In [15]:
Quan

['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']

In [16]:
Qual

['rbc',
 'pc',
 'pcc',
 'ba',
 'pcv',
 'wc',
 'rc',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

In [17]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

# Using Central Tendancy method

In [19]:
dataset[Quan]

      id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2    NaN  NaN  15.4
1      1   7.0  50.0  1.020  4.0  0.0    NaN  18.0  0.8    NaN  NaN  11.3
2      2  62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8    NaN  NaN   9.6
3      3  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4      4  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4    NaN  NaN  11.6
..   ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

In [20]:
dataset["age"].mean()

51.48337595907928

In [21]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(dataset[Quan])
dataset=imp.transform(dataset[Quan])

In [22]:
dataset

array([[  0.        ,  48.        ,  80.        , ..., 137.52875399,
          4.62724359,  15.4       ],
       [  1.        ,   7.        ,  50.        , ..., 137.52875399,
          4.62724359,  11.3       ],
       [  2.        ,  62.        ,  80.        , ..., 137.52875399,
          4.62724359,   9.6       ],
       ...,
       [397.        ,  12.        ,  80.        , ..., 137.        ,
          4.4       ,  15.8       ],
       [398.        ,  17.        ,  60.        , ..., 135.        ,
          4.9       ,  14.2       ],
       [399.        ,  58.        ,  80.        , ..., 141.        ,
          3.5       ,  15.8       ]])

In [23]:
dataset=pd.DataFrame(dataset)

In [24]:
dataset

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.0,48.0,80.0,1.020,1.0,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4
1,1.0,7.0,50.0,1.020,4.0,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3
2,2.0,62.0,80.0,1.010,2.0,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6
3,3.0,48.0,70.0,1.005,4.0,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2
4,4.0,51.0,80.0,1.010,2.0,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6
...,...,...,...,...,...,...,...,...,...,...,...,...
395,395.0,55.0,80.0,1.020,0.0,0.0,140.000000,49.0,0.5,150.000000,4.900000,15.7
396,396.0,42.0,70.0,1.025,0.0,0.0,75.000000,31.0,1.2,141.000000,3.500000,16.5
397,397.0,12.0,80.0,1.020,0.0,0.0,100.000000,26.0,0.6,137.000000,4.400000,15.8
398,398.0,17.0,60.0,1.025,0.0,0.0,114.000000,50.0,1.0,135.000000,4.900000,14.2
399,399.0,58.0,80.0,1.025,0.0,0.0,131.000000,18.0,1.1,141.000000,3.500000,15.8

# missing values have been added.

In [25]:
dataset.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
dtype: int64

# Measure of Central Tendancy

In [30]:
dataset["age"].mean()

51.48337595907928

In [31]:
dataset["age"].median()

55.0

In [32]:
dataset["age"].mode()[0]

60.0

In [33]:
dataset.describe()

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
count,400.000000,391.000000,388.000000,353.000000,354.000000,351.000000,356.000000,381.000000,383.000000,313.000000,312.000000,348.000000
mean,199.500000,51.483376,76.469072,1.017408,1.016949,0.450142,148.036517,57.425722,3.072454,137.528754,4.627244,12.526437
std,115.614301,17.169714,13.683637,0.005717,1.352679,1.099191,79.281714,50.503006,5.741126,10.408752,3.193904,2.912587
min,0.000000,2.000000,50.000000,1.005000,0.000000,0.000000,22.000000,1.500000,0.400000,4.500000,2.500000,3.100000
25%,99.750000,42.000000,70.000000,1.010000,0.000000,0.000000,99.000000,27.000000,0.900000,135.000000,3.800000,10.300000
50%,199.500000,55.000000,80.000000,1.020000,0.000000,0.000000,121.000000,42.000000,1.300000,138.000000,4.400000,12.650000
75%,299.250000,64.500000,80.000000,1.020000,2.000000,0.000000,163.000000,66.000000,2.800000,142.000000,4.900000,15.000000
max,399.000000,90.000000,180.000000,1.025000,5.000000,5.000000,490.000000,391.000000,76.000000,163.000000,47.000000,17.800000

In [34]:
describe=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5RULE","LESSER","GREATER","min","max","skew","kurtosis"],columns=Quan)
for columnName in Quan:
        describe[columnName]["mean"]=dataset[columnName].mean()
        describe[columnName]["median"]=dataset[columnName].median()
        describe[columnName]["mode"]=dataset[columnName].mode()[0]
        describe[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
        describe[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
        describe[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
        describe[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
        describe[columnName]["IQR"]=describe[columnName]["Q3:75%"]-describe[columnName]["Q1:25%"]
        describe[columnName]["1.5RULE"]=1.5*describe[columnName]["IQR"]
        describe[columnName]["LESSER"]=describe[columnName]["Q1:25%"]-describe[columnName]["1.5RULE"]
        describe[columnName]["GREATER"]=describe[columnName]["Q3:75%"]+describe[columnName]["1.5RULE"]
        describe[columnName]["min"]=dataset[columnName].min()
        describe[columnName]["max"]=dataset[columnName].max()
        describe[columnName]["skew"]=dataset[columnName].skew()
        describe[columnName]["kurtosis"]=dataset[columnName].kurtosis()

In [35]:
describe

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
mean,199.5,51.4834,76.4691,1.01741,1.01695,0.450142,148.037,57.4257,3.07245,137.529,4.62724,12.5264
median,199.5,55,80,1.02,0,0,121,42,1.3,138,4.4,12.65
mode,0,60,80,1.02,0,0,99,46,1.2,135,3.5,15
Q1:25%,99.75,42,70,1.01,0,0,99,27,0.9,135,3.8,10.3
Q2:50%,199.5,55,80,1.02,0,0,121,42,1.3,138,4.4,12.65
Q3:75%,299.25,64.5,80,1.02,2,0,163,66,2.8,142,4.9,15
Q4:100%,399,90,180,1.025,5,5,490,391,76,163,47,17.8
IQR,199.5,22.5,10,0.01,2,0,64,39,1.9,7,1.1,4.7
1.5RULE,299.25,33.75,15,0.015,3,0,96,58.5,2.85,10.5,1.65,7.05
LESSER,-199.5,8.25,55,0.995,-3,0,3,-31.5,-1.95,124.5,2.15,3.25
GREATER,598.5,98.25,95,1.035,5,0,259,124.5,5.65,152.5,6.55,22.05
min,0,2,50,1.005,0,0,22,1.5,0.4,4.5,2.5,3.1
max,399,90,180,1.025,5,5,490,391,76,163,47,17.8
skew,0,-0.668259,1.60543,-0.172444,0.998157,2.46426,2.01077,2.63437,7.50954,-6.99657,11.583,-0.335095
kurtosis,-1.2,0.0578405,8.6461,-1.14436,-0.383377,5.05535,4.22559,9.34529,79.3043,85.5344,142.506,-0.471398

# outlier has been found &replaced.

In [36]:
describe["age"]["min"]<describe["age"]["LESSER"]

True

In [37]:
LESSER=[]
GREATER=[]
for columnName in Quan:
    if(describe[columnName]["min"]<describe[columnName]["LESSER"]):
        LESSER.append(columnName)
    if(describe[columnName]["max"]>describe[columnName]["GREATER"]):
        GREATER.append(columnName)

In [38]:
LESSER

['age', 'bp', 'sod', 'hemo']

In [39]:
GREATER

['bp', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot']

In [52]:
for columnName in LESSER:
    dataset[columnName][dataset[columnName]<describe[columnName]["LESSER"]]=describe[columnName]["LESSER"]
for columnName in GREATER:
    dataset[columnName][dataset[columnName]>describe[columnName]["GREATER"]]=describe[columnName]["GREATER"]

C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [53]:
describe=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5RULE","LESSER","GREATER","min","max","skew","kurtosis"],columns=Quan)
for columnName in Quan:
        describe[columnName]["mean"]=dataset[columnName].mean()
        describe[columnName]["median"]=dataset[columnName].median()
        describe[columnName]["mode"]=dataset[columnName].mode()[0]
        describe[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
        describe[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
        describe[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
        describe[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
        describe[columnName]["IQR"]=describe[columnName]["Q3:75%"]-describe[columnName]["Q1:25%"]
        describe[columnName]["1.5RULE"]=1.5*describe[columnName]["IQR"]
        describe[columnName]["LESSER"]=describe[columnName]["Q1:25%"]-describe[columnName]["1.5RULE"]
        describe[columnName]["GREATER"]=describe[columnName]["Q3:75%"]+describe[columnName]["1.5RULE"]
        describe[columnName]["min"]=dataset[columnName].min()
        describe[columnName]["max"]=dataset[columnName].max()
        describe[columnName]["skew"]=dataset[columnName].skew()
        describe[columnName]["kurtosis"]=dataset[columnName].kurtosis()

In [54]:
describe

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
mean,199.5,51.5512,75.6959,1.01741,1.01695,0,139.972,51.7643,2.13133,138.208,4.39006,12.5269
median,199.5,55,80,1.02,0,0,121,42,1.3,138,4.4,12.65
mode,0,60,80,1.02,0,0,259,124.5,5.65,135,3.5,15
Q1:25%,99.75,42,70,1.01,0,0,99,27,0.9,135,3.8,10.3
Q2:50%,199.5,55,80,1.02,0,0,121,42,1.3,138,4.4,12.65
Q3:75%,299.25,64.5,80,1.02,2,0,163,66,2.8,142,4.9,15
Q4:100%,399,90,95,1.025,5,0,259,124.5,5.65,152.5,6.55,17.8
IQR,199.5,22.5,10,0.01,2,0,64,39,1.9,7,1.1,4.7
1.5RULE,299.25,33.75,15,0.015,3,0,96,58.5,2.85,10.5,1.65,7.05
LESSER,-199.5,8.25,55,0.995,-3,0,3,-31.5,-1.95,124.5,2.15,3.25
GREATER,598.5,98.25,95,1.035,5,0,259,124.5,5.65,152.5,6.55,22.05
min,0,8.25,55,1.005,0,0,22,1.5,0.4,124.5,2.5,3.25
max,399,90,95,1.025,5,0,259,124.5,5.65,152.5,6.55,17.8
skew,0,-0.61576,0.090421,-0.172444,0.998157,0,1.02296,1.07887,1.15381,-0.183473,0.383004,-0.331398
kurtosis,-1.2,-0.109481,-0.975988,-1.14436,-0.383377,0,-0.177305,0.0259568,-0.088975,-0.0583077,0.311595,-0.486354

In [55]:
LESSER=[]
GREATER=[]
for columnName in Quan:
    if(describe[columnName]["min"]<describe[columnName]["LESSER"]):
        LESSER.append(columnName)
    if(describe[columnName]["max"]>describe[columnName]["GREATER"]):
        GREATER.append(columnName)

In [56]:
LESSER

[]

In [57]:
GREATER

[]

# frequency table.

In [58]:
def freqtable(columnName,dataset):
    freqtable=pd.DataFrame(columns=["unique_value","freq","relative_freq","cumsum"])
    freqtable["unique_value"]=dataset[columnName].value_counts().index
    freqtable["freq"]=dataset[columnName].value_counts().values
    freqtable["relative_freq"]=(freqtable["freq"]/133)
    freqtable["cumsum"]=freqtable["relative_freq"].cumsum()
    return freqtable

In [59]:
freqtable("age",dataset)

    unique_value  freq  relative_freq    cumsum
0           60.0    19       0.142857  0.142857
1           65.0    17       0.127820  0.270677
2           55.0    12       0.090226  0.360902
3           50.0    12       0.090226  0.451128
4           48.0    12       0.090226  0.541353
..           ...   ...            ...       ...
65          27.0     1       0.007519  2.909774
66          83.0     1       0.007519  2.917293
67          90.0     1       0.007519  2.924812
68          78.0     1       0.007519  2.932331
69          26.0     1       0.007519  2.939850

[70 rows x 4 columns]